{
 "title": "Docker Monitoring",
 "tags": [
  "monitoring",
  "linux",
  "bbh",
  "docker"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "agent",
    "query": "SHOW TAG VALUES FROM cpu WITH KEY = \"host\""
   }
  ]
 },
 "panels": [
  {
   "title": "System Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "measurement": "system",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$agent$/" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Running Containers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "docker",
     "select": [
      [
       { "params": [ "n_containers" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$agent$/" }
     ]
    }
   ]
  },
  {
   "title": "Current Load (load1)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$agent$/" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Current Memory Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mem",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$agent$/" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Docker Disk Space Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent", "label": "Disk Used %" }
   ],
   "targets": [
    {
     "alias": "disk.used",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disk",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$agent$/" },
      { "condition": "AND", "key": "path", "operator": "=", "value": "/" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Docker CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "docker.cpu",
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "docker_container_cpu",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$agent$/" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Docker Memory Stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "docker_container_mem",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "select": [
      [
       { "params": [ "usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "usage" ], "type": "alias" }
      ],
      [
       { "params": [ "rss" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "rss" ], "type": "alias" }
      ],
      [
       { "params": [ "cache" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "cache" ], "type": "alias" }
      ],
      [
       { "params": [ "pgfault" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "pgfault" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$agent$/" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Running Docker Containers",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "container_image" ], "type": "tag" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "io.rancher.container.ip" ], "type": "tag" },
      { "params": [ "io.rancher.stack.name" ], "type": "tag" }
     ],
     "measurement": "docker_container_blkio",
     "select": [
      [
       { "params": [ "container_id" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "Container ID" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$agent$/" }
     ]
    }
   ]
  }
 ]
}